### ISSUE TITLE
Check for issues with a blocked remote port

### ISSUE THREAD

**Issue by fmauch** [UniversalRobots/Universal_Robots_ExternalControl_URCap#1]
As raised in UniversalRobots/Universal_Robots_ROS_Driver#74 there's the suspicion that once this URCap is installed, a connection attempt is being performed in each program launch.

This can lead to problems when the remote port is blocked e.g. by a firewall.

To clairfy: Does the `generate_script` function from the InstallationNodeContribution get called even when the node is not part of the program tree? Edit: It does.

**Comment by gavanderhoorn** [comment]
Seeing #2: the urcap was trying to connect always? Regardless of whether it was being used?

**Comment by fmauch** [comment]
Yes, as this was in the script_generating part of the InstallationNode. This is called for every URCap installed (and not disabled) once a program gets compiled.
