### ISSUE TITLE
Simple test server

### ISSUE THREAD

**Issue by urrsk** [UniversalRobots/Universal_Robots_ExternalControl_URCap#21]
I have made a simple python3 test server to be used together with the External Control URCap.
In the future, It could be used as a tool for testing the URCap, as well as a simple tool to test script code on the robot.

But where should I place it? in a 'example' or 'test'?

**Comment by fmauch** [comment]
If we can wrap it into a maven test, test would be the correct location. Otherwise, I would suggest using `example`

**Comment by fmauch** [comment]
I think this can be closed by now...
