### ISSUE TITLE
UR5e extrapolating the trajectory control command send via ROS at 50Hz

### ISSUE THREAD

**Issue by nitish3693** [UniversalRobots/Universal_Robots_ExternalControl_URCap#26]
I using the external control URCap to communicate to the UR using ROS. The trajectory control command is generated in ROS at 50Hz but since the UR5e operates at 500Hz it seems to be extrapolating the command which results in higher acceleration and velocities compared to ROS. 

Could you suggest if URscript is interpolating the ROS trajectory command linearly or projecting the command and correcting when it receive new one while doing the extrapolation?

**Comment by fmauch** [comment]
Why would you come to the assumption, that control commands are only sent with 50 Hz?

**Comment by nitish3693** [comment]
I am using a custom publisher which publishes the trajectory command calculated using custom IK script to the ROS topic `/scaled_pos_joint_traj_controller/follow_joint_trajectory/goal` at 50Hz.

**Comment by nitish3693** [comment]
We are using the driver file [ur5e_bringup.launch](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/launch/ur5e_bringup.launch) from the [repository](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver)  for establishing the connection to the URCap [externalcontrol-1.0.5.urcap](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/resources/externalcontrol-1.0.5.urcap).

The Figure 1 below shows the update of `/scaled_pos_joint_traj_controller/follow_joint_trajectory/goal.goal.trajectory.points[0].positions[4]` and  `/scaled_pos_joint_traj_controller/follow_joint_trajectory/goal.goal.trajectory.points[0].velocities[4]` from the trajectory command generated using our custom IK scripts to node `/ur_hardware_interface`  

![image](https://user-images.githubusercontent.com/75649112/146649659-71b97d5c-f996-49c1-a160-88aaab709f09.png)


![image](https://user-images.githubusercontent.com/75649112/146648763-670e3da6-2694-49eb-b33f-b136dc660540.png)
Figure 1 : Joint 4 Position and Velocity Graph

**Comment by nitish3693** [comment]
This is the result from the UR Log Viewer. This there a way to make the Velocity, acceleration and currents smoother. The Joint Position as shown in the result is smooth.

![image](https://user-images.githubusercontent.com/75649112/146681621-6af9b6b2-a157-4ccb-aaef-b3938701849a.png)

**Comment by nitish3693** [comment]
Velocity and Position command for the Joint 0 sent from our package to `/ur_hardware_interface` for a sine wave motion recorded using rosbag : 
![image](https://user-images.githubusercontent.com/75649112/146681794-c6b861d9-a27c-4d78-b04b-fc8ae3e1c656.png)

**Comment by Changliu52** [comment]
@fmauch 
It looks there is obvious added velocity noise from the 'ur_hardware_interface', when it outputs to the robot.
Despite the command input to the 'ur_hardware_interface' was smooth.

Also adjusting the value in the PID gains or velocity_ff in https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/config/ur5e_controllers.yaml made no observable difference in performance.

**Comment by fmauch** [comment]
You are using the scaled trajectory controller to interface the robot. This controller is generating trajectories based on the input given. In the [example above](https://github.com/UniversalRobots/Universal_Robots_ExternalControl_URCap/issues/26#issuecomment-997205792), a trajectory with one setpoint is given. The Setpoint should be reached in 20 ms. The controller now creates a trajectory from the current configuration to the target configuration using a spline interpolation (This is basically, how the joint trajectory controller works). This generated motion is then sampled by the hardware interface (through the controller implementation) in each control cycle (with 500Hz) to generate commands sent to the robot.

Thus, the robot is not "simply going there".

The "noise" mentioned in https://github.com/UniversalRobots/Universal_Robots_ExternalControl_URCap/issues/26#issuecomment-997419579 comes from the fact, that a `servoj` command is used to [execute the commands](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/c3378599d5fa73a261328b326392e847f312ab6b/ur_robot_driver/resources/ros_control.urscript?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L71). The actual behavior of this `servoj` command can be altered by changing the values for [`servoj_gain`](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/c3378599d5fa73a261328b326392e847f312ab6b/ur_robot_driver/launch/ur_control.launch?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L32) and [`servoj_lookahead_time`](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/c3378599d5fa73a261328b326392e847f312ab6b/ur_robot_driver/launch/ur_control.launch?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L33).

For real smooth velocities, a velocity-based controller such as the `scaled_vel_joint_traj_controller` could be used. Please see the [controller documentation](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/doc/controllers.md) for details on the available controllers.

**Comment by Changliu52** [comment]
Thank you for the information.  @fmauch 
We have tested that reducing the `servoj_gain` reduces the jitters significantly. It seems putting it to 100 (minimal) instead of 2000 (default also maximum) gives the best smoothness in simulation. 

Hopefully it will not compromise too much on the control precision?
