### ISSUE TITLE
External Control doesn't work on Macbook

### ISSUE THREAD

**Issue by totototo96** [UniversalRobots/Universal_Robots_ExternalControl_URCap#27]
Hi Everyone,
I've problem with connection of the UR5e with my Docker image installed on my Macbook (version 2017). The ur5e and my Macbook are connected via router with lan cables. When I do the connection with `roslaunch ur_calibration calibration_correction.launch robot_ip:=[ROBOT_IP] target_filename:="${HOME}/my_robot_calibration.yaml"` the PC see the UR5e but when I do the connection with `external control`, for move it, on the tablet of the UR5e with the IP address of my MacBook, I have the error: `The connection to the remote PC at [ROBOT_IP] could not be established..`. 
I've disabled on my Macbook the Firewall, but the robot still not connected. I don't know why I have this problem because on the other machine that I use with Ubuntu 18.04 work perfectly. Maybe the problem could be the "hub usb c -> lan"?
How can I resolve this problem?

Thanks a lot for your help guys!

Docker Image version:
- Ubuntu 18.04
- Ros-Melodic
MacBook (2017 with usb-c):
- Mac OS Monterey 12.3

**Comment by fmauch** [comment]
You'll have to make sure to forward ports 50001, 50002, 50003 from your ubuntu docker to your macbook if you want to do such a thing.

```
docker run -p 50001-50003:50001:50003 ...
```

I hope, this helps

**Comment by totototo96** [comment]
Hi @fmauch! 
Thanks a lot for your helping! 
Now I'm using a `docker-compose` for launching the .yml file with 5 different containers, in this case attaching: modim, pnp, xserver, nginx and the last container "simulator" where are located all the files of the UR5e. 
How can I manage with these to put inside the ports in ".yml" file?

Really Thanks!

**Comment by fmauch** [comment]
This goes beyond the scope of this driver repo. In general, please see the documentation of docker-compose. To my knowledge you won't have to do any treatment of the ports for the services to talk to each other. If you want to expose ports from one of your services, use the `ports` flag from docker-compose (see the [docs](https://docs.docker.com/compose/networking/)).

I assume that questions regarding this driver have been clarified and I will therefore close this issue. If this is not the case, feel free to comment and / or reopen.
