### ISSUE TITLE
How to set Remote IP address and port once? 

### ISSUE THREAD

**Issue by Mechazo11** [UniversalRobots/Universal_Robots_ExternalControl_URCap#32]
Hi @fmauch 

Everytime we need to invoke the ExternalControl URCap from Polyscope, the Remote IP address and custom port gets set to a default value.

Is there a way to set these values once?

With best,
@Mechazo11

**Comment by fmauch** [comment]
Hey there. Please do not at-mention people directly when creating issues unless there is a clear relation to a previously discussed matter. Issue trackers are often watched by multiple people. Mentioning people directly raises unnecessary noise in their inboxes.

That being said: I assume you changed the remote host and IP in the installation settings. Did you save your installation afterwards? Without saving it will work for the current run, but once the robot is rebooted it will load the saved values from the installation.

**Comment by Mechazo11** [comment]
Hello,

Sorry for the oversight. I will keep it mind for next time.

Yes, the problem went away the way you described it. As soon as I saved it, the settings remain stable for the consecutive runs.

With best,
@Mechazo11
