### ISSUE TITLE
Source code not up2date?

### ISSUE THREAD

**Issue by ipa-lth** [UniversalRobots/Universal_Robots_ExternalControl_URCap#4]
It seems like the content of https://github.com/UniversalRobots/Universal_Robots_ExternalControl_URCap is not the source code of [externalcontrol-1.0.1.urcap](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/resources/externalcontrol-1.0.1.urcap).

[externalcontrol-1.0.1.urcap](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/resources/externalcontrol-1.0.1.urcap) offers two InputFields on the InstallationTab; while InstallationView defines three Fields with different texts.

Could you please update the sources?

**Comment by fmauch** [comment]
Thanks for bringing that up, I will check that.

**Comment by ipa-lth** [comment]
ping

**Comment by fmauch** [comment]
Yep, I'll release a new version today.

**Comment by fmauch** [comment]
Closing this as v1.0.2 has been merged a while ago.
